<?php

namespace App\Patterns\Delegation\Classes;

class EmailMessenger extends AbstractMessenger
{
    public function send(): bool
    {
        \Debugbar::info('sent by' . __METHOD__);
        return parent::send(); // TODO: Change the autogenerated stub
    }

}
